# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(F0F2FE)
$foreground = rgb(050C22)
$color0 = rgb(FDFEFF)
$color1 = rgb(4C567F)
$color2 = rgb(3A456C)
$color3 = rgb(2F455B)
$color4 = rgb(0E1A3F)
$color5 = rgb(081439)
$color6 = rgb(081439)
$color7 = rgb(050C22)
$color8 = rgb(656E94)
$color9 = rgb(6673AA)
$color10 = rgb(4D5C90)
$color11 = rgb(3E5C79)
$color12 = rgb(132254)
$color13 = rgb(0B1A4C)
$color14 = rgb(0B1A4C)
$color15 = rgb(02040B)
