# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #050C22
background         #F0F2FE
cursor             #293459

active_tab_foreground     #F0F2FE
active_tab_background     #050C22
inactive_tab_foreground   #050C22
inactive_tab_background   #F0F2FE

active_border_color   #050C22
inactive_border_color #F0F2FE
bell_border_color     #4C567F

color0      #FDFEFF
color1		#4C567F
color2		#3A456C
color3		#2F455B
color4		#0E1A3F
color5		#081439
color6		#081439
color7		#050C22
color8		#656E94
color9		#6673AA
color10		#4D5C90
color11		#3E5C79
color12		#132254
color13		#0B1A4C
color14		#0B1A4C
color15		#02040B
